server:
  port: 8000
spring:
  application:
    name: mvs-jinmai-manager-web
  redis:
    host: 192.168.50.59
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
management:
  endpoints:
    web:
      enposure:
        include: "*"
